Newstyle
sparcs-kaist/wedalias pull request #2
Opened 2019-03-04 16:29 UTC by jwoo0122

스타일 정리

2019-03-04 16:36 UTC, Medowhill requested changes
static/image 디렉토리 이름 static/images 로 바꿔주세요

2019-03-04 16:37 UTC, Medowhill reviewed
로그인페이지랑 다른 페이지 Members by SPARCS 다르게 생긴건 일부러 그렇게 하는건가요?

2019-03-04 16:41 UTC, Medowhill reviewed
passwd 페이지에서 "현재 비밀번호", "새 비밀번호", "새 비밀번호 확인" 길이가 다 다른데 똑같게 맞춰주는게 좋을까요아니면 지금 이 상태가 좋을까요?

2019-03-04 16:45 UTC, Medowhill reviewed
"포워딩 메일 설정" 보다는 "메일 포워딩 설정" 이 자연스러운거 같은데 어떻게 생각하시나요?

2019-03-04 16:56 UTC, jwoo0122 commented
- 헤더 디자인은 통일할게요.
- 인풋 글자 길이는 통일을 해볼까 생각중인데, 크게 중요한 부분은 아니라 나중에 해도 괜찮을 것 같아요.
- 포워딩 메일 설정은 직역이었습니다. 바꿔볼게요.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

2019-03-04 17:04 UTC, Medowhill commented
인풋 글자 길이는 별도 이슈로 분리했습니다. :) #4

2019-03-05 01:36 UTC, samjo-nyang commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
8글자 제한 외에 숫자, 특수문자를 섞도록 하는 이유가 있는지 궁금합니다.

https://pages.nist.gov/800-63-3/sp800-63b.html#sec5
> Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets.

2019-03-05 01:49 UTC, jwoo0122 commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
일종의 관례라고 보면 되지 않을까요?

https://blog.devolutions.net/2018/02/top-10-password-policies-and-best-practices-for-system-administrators

2019-03-05 02:25 UTC, samjo-nyang commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
생각해보니 우리 서버에는 취약한 password 검사기가 없네요... 문자 섞도록 하는게 더 좋을거 같습니다 ㅠㅠ

+ 그 관례는 좋은 관례가 아닌것 같습니다.
https://www.theverge.com/2017/8/7/16107966/password-tips-bill-burr-regrets-advice-nits-cybersecurity

2019-03-05 02:34 UTC, jwoo0122 commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
흥미로운 글이네요!

2019-03-05 10:15 UTC, Medowhill commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
회원들이 매우 짧은 평문이나 유저네임과 패스워드를 동일하게 함으로 인하여 계정을 탈취당했던 사례들 때문에 웹사이트에서 패스워드 변경 할 때라도 좀 더 안전한 패스워드를 사용하게 하려는 뜻이었는데 좋은 방법은 아니었군요... 랜덤 스트링 생성해서 비밀번호를 사용하면 특수문자 조건이 괜찮을거 같지만 그걸 모든 회원들한테 기대할수는 없으니 ㅠ
`16자 이상의 영문 대소문자` 로 바꿀까요?

2019-03-05 10:19 UTC, Medowhill commented on static/views/passwd.ejs
> +        <p>최소 하나의 영문 대/소문자, 숫자, 특수문자를 사용하세요.</p>
#5 패스워드는 별도 이슈로 분리했습니다

2019-03-05 10:25 UTC, Medowhill approved these changes
LGTM 👍

2019-03-05 10:25 UTC, merged